Makefile: Add install target
projecthamster/shell-extension pull request #330
Opened 2020-04-29 00:14 UTC by amboar

Script some of the behaviour previously captured in the readme as
instructions to execute manually.

Signed-off-by: Andrew Jeffery <andrew@aj.id.au>

2020-04-29 17:04 UTC, benjaoming requested changes
Love this! Thanks @amboar! Wondering if `make install` is better as `make install-user` or similar ?

2020-04-29 17:04 UTC, benjaoming commented on Makefile
> +install: dist
Great! I wrote the steps in the README, happy to see them in the Makefile! Can we rename this to `install-user` ? It's because `sudo make install` won't do a system-wide installation which might be expected (that needs a slightly different path, but it's also doable).

2020-04-29 22:56 UTC, amboar commented on Makefile
> +install: dist
Right, I initially called it `install-local` but I think your suggestion of `install-user` is better. I'll rework it shortly.

2020-04-30 13:44 UTC, mwilck requested changes
See inline comments.

2020-04-30 13:44 UTC, mwilck commented on Makefile
> +	rm -rf ${HOME}/.local/share/gnome-shell/extensions/contact@projecthamster.org
I'd rather do this in a separate step, call it `clean-install`, `uninstall-local`, or whatever. Deleting stuff in the user's home directory, outside the build dir itself, might come to an unpleasant surprise to some people.

2020-04-30 13:44 UTC, mwilck commented on Makefile
> +	# Unpack build
I'd prefer unpacking the zip inside some subdir of the build directory itself, and just using a symlink from `${HOME}/.local/share/gnome-shell/extensions` to that subdir. (This is how I do it here :grin:).

Whether `make` should create that symlink should or just print a message informing the user how to do it would be up to discussion. I'd prefer the latter.

(Edit) actually, the sources are already unpacked in the final form under `build`. So creating symlink to that directory would be sufficient. Not sure if we want that though, `build` might be overwritten with experimental code.

2020-04-30 14:45 UTC, benjaoming commented on Makefile
> +	# Unpack build
@mwilck I don't think a normal user wants that?

I expect to be able to delete the whole build structure after installing.

2020-04-30 14:49 UTC, benjaoming commented on Makefile
> +	rm -rf ${HOME}/.local/share/gnome-shell/extensions/contact@projecthamster.org
I think it's expected from `make install-user` to delete the existing extension.

> Deleting stuff in the user's home directory, outside the build dir itself, might come to an unpleasant surprise to some people.

This isn't "stuff", this is `${HOME}/.local/share/gnome-shell/extensions/contact@projecthamster.org`

Someone running `make install-user` shouldn't be surprised that this command overwrites an existing extension. That's what all software installers would do: Upgrade an existing previous installation.

2020-04-30 14:58 UTC, mwilck commented
Before we merge this, we should clarify if we want to have it on `develop` only or also on our other branches. In the latter case, we need to create the branches first, and start merging to the "lowest" one we want to support.

2020-05-04 15:33 UTC, hedayat commented on Makefile
> +install: dist
I think install target should depend on `compile`, and copy files directly to target directory. No need to create and archive and then extract it again!

2020-05-04 15:33 UTC, hedayat commented on Makefile
> +	mkdir -p ${HOME}/.local/share/gnome-shell/extensions/contact@projecthamster.org
I think it should be installed to system-wide directory by default. You might make it possible to specify if it should be installed system-wide or into user's home directory.

Also, it should be possible to provide an installation prefix (DESTDIR) at least for system-wide installations. 

Thanks!

2020-05-04 15:34 UTC, hedayat commented
Oops, sorry guys. I wrote my comments 4days ago, but didn't know that I should press "Submit review" :D

2020-05-04 16:25 UTC, benjaoming commented on Makefile
> +	mkdir -p ${HOME}/.local/share/gnome-shell/extensions/contact@projecthamster.org
That's not the point of this PR: It's automating the instructions for a local user installation.

@amboar will change the name of the make target to `install-user`. The other name is thus free for implementing a system-wide installation for some other purpose, perhaps in a fakeroot for packaging.

2020-05-04 16:26 UTC, benjaoming commented on Makefile
> +install: dist
This works fine though? And `dist` already exists? `dist` might do other things in the future, so I think it's best to keep stuff clean: `build=>dist=>install`, that's AFAIK a normal procedure.

2020-05-04 17:09 UTC, DirkHoffmann commented
Trying to summarise what was written above: There are three targets,

- `install-user` : to `~/.local/share/gnome-shell/extensions/contact@projecthamster.org/`
- `install` : system-wide
- `dist` : create ZIP for submission to extensions.gnome.org

and they should all depend on `compile`. And `install*` depends on `dist`.

Sounds plausible to me.

2020-05-04 21:00 UTC, hedayat commented on Makefile
> +install: dist
Well, `compile` already exists too. And no, `build=>install` is a normal procedure. `dist` target is usually used to create distribution packages (e.g. in autotools world), and is usually not used for anything else. Actually, I've never seen `build=>dist=>install` myself. 

Anyway, I gave my suggestion, and I won't push for it much. But still, I think that makes more sense.

2020-05-04 21:01 UTC, hedayat commented on Makefile
> +	mkdir -p ${HOME}/.local/share/gnome-shell/extensions/contact@projecthamster.org
Well, the title and description doesn't tell it, at least explicitly. And, it is fairly easy to add. But if  the author is not willing to provide that, I'm fine.`

2020-05-04 21:04 UTC, hedayat commented
>     * `dist` : create ZIP for submission to extensions.gnome.org
> 
> and they should all depend on `compile`. And `install*` depends on `dist`.

You already contradicted yourself: install* depends on dist, while dist creates an archive for submission to EGO (and install* doesn't submit the archive to EGO) :D ;)

Anyway, if you all like that, go with it. Simply, I don't. :)

2020-05-04 21:12 UTC, benjaoming commented
@mwilck 

> Before we merge this, we should clarify if we want to have it on develop only or also on our other branches. In the latter case, we need to create the branches first, and start merging to the "lowest" one we want to support.

It's true, removing the old instructions from README and replacing them with instructions that only work with the current `develop` branch isn't ideal.

@amboar What do you think about keeping the old instructions and instead add something like this?

> #### Shortcut on `develop`
>
> If you are using the `develop` branch since May 2020, you can run `make install-user` to install your current working branch in your user environment

2020-05-05 01:20 UTC, amboar commented on Makefile
> +	mkdir -p ${HOME}/.local/share/gnome-shell/extensions/contact@projecthamster.org
> Well, the title and description doesn't tell it, at least explicitly

That's because the request to switch to `install-user` came after I made the PR. I've agreed to make the change.

2020-05-05 01:28 UTC, amboar commented
To be honest I didn't expect the PR to drive so much discussion. The patch made my life easier testing @mwilck 's 3.36 changes and I figured I might as well propose it. I'm not attached to it and am happy to drop it if we feel it's taking more energy to handle than is necessary.

I feel like applying it to `develop` only causes a bit of a maintenance headache, though I'm only guessing at how you manage your branches. That said I'm not living with the maintenance problem so I don't mind if you want to pick it up. I'll rework the readme as you suggest @benjaoming.

Addressing the `dist` vs `compile` target discussion, reusing `dist` was the path of least resistance as that was what was described in the readme. I think the question of whether we should conform more accurately to autotools semantics can be sorted out separately? I agree that how `dist` is implemented here doesn't really align with the `dist` target of autotools.

2020-05-05 03:00 UTC, amboar commented
So with what I've just pushed we now have both `install` and `install-user` targets. I've split the patches out so you can take as many as you think are reasonable :) The `install-user` patch comes before the addition of `install` because it's more obviously a direct translation of the instructions in the README. The addition of `install` exposes and uses the `DESTDIR` variable so we can adjust the target installation path, which I then make use of to (re-)implement `install-user`. Finally the documentation is updated separate to either patch so if it's still contentious whether the patches should apply to master or not you can pick the others into `develop` while that discussion continues.

The targets still depend on `dist`, I haven't tackled the idea of making them instead depend on `compile`.

2020-05-05 08:33 UTC, benjaoming approved these changes
This is awesome! Thanks so much @amboar

2020-05-05 08:33 UTC, benjaoming commented on README.rst
> +distribution archive::
:100:

2020-05-05 09:06 UTC, mwilck approved these changes

2020-05-05 09:12 UTC, mwilck commented
@amboar ,

> To be honest I didn't expect the PR to drive so much discussion. 

That's how it goes when you make contributions to OSS projects, right? No matter how simple you think it would be, suddenly it gets a big issue :grin:   
I'm sorry that I had my part in that, I guess I was a bit overzealous.

Thanks a lot for your contribution.

2020-05-05 10:02 UTC, amboar commented
> @amboar ,
> 
> > To be honest I didn't expect the PR to drive so much discussion.
> 
> That's how it goes when you make contributions to OSS projects, right? No matter how simple you think it would be, suddenly it gets a big issue grin
> I'm sorry that I had my part in that, I guess I was a bit overzealous.

No, don't apologise! I'm just a drive-by contributor and have zero stake in ongoing maintenance, so I would have been fine with any response let alone possibly getting it merged. It just seemed like a simple enough change that I was just expecting "yeah, let's merge" or "nah, reasons, closed" 🙂 

> 
> Thanks a lot for your contribution.

No worries - thanks for taking the time to look at it and respond.

2020-05-05 10:57 UTC, benjaoming commented on README.rst
> +*Shortcut on ``develop``*
```suggestion
**Shortcut on** `develop`
```

(the inline code didn't render well on GH)

2020-05-05 10:58 UTC, benjaoming commented on README.rst
> +**Shortcut on** `develop`
```suggestion
**Shortcut on** ``develop``
```

2020-05-05 10:59 UTC, benjaoming commented
This is a positive improvements that received some suggestions, but no real concerns, so it should be good to go.

(sorry about the extra commit, using Github Suggestions wasn't ideal for quick fingers)

2020-05-08 21:39 UTC, DirkHoffmann commented
Hi guys, 
This seems to have converged. I just "resolved" (I.e. collapsed) the three "conversations" for cleanup.
This PR now needed an assignee, and while every one of the reviewers would be fine, I have randomly choosen the first who answered. Anyone who is faster can change this again. :-) 
@amboar, just to give you some context, the four reviewers/managers who answered on this ticket are only in charge since March this year. So your proposal came in a period, where we still have to find our way with the github process, and it served as an example for that as well. Thank you very much for your input and fast feedback!

2020-05-09 07:44 UTC, merged